/**
 * Cleans the content of a workout section by removing markdown and list markers.
 * @param content The raw string content of a section.
 * @returns A cleaned-up string with each item on a new line.
 */
const cleanContent = (content: string): string => {
  if (!content) return '';
  return content
    .split('\n')
    .map(line => line.trim())
    .filter(line => line)
    .map(line => line.replace(/^(\* |- |➤) ?/, '').replace(/\*\*/g, '').replace(/&#10148; ?/g, ''))
    .join('\n');
};

/**
 * Formats a workout markdown string into a plain text format for easy copying to Slack.
 * @param markdownText The full workout generated by the AI.
 * @returns A formatted string with WARMUP, THE THANG, MARY, ANNOUNCEMENTS, and COT sections.
 */
export const formatWorkoutForExport = (markdownText: string): string => {
  const sections: { [key: string]: string } = {
    'WARMUP': '',
    'THE THANG': '',
    'MARY': '',
    'COT': '',
  };

  // Regex to find all section headers. The 'g' flag is crucial for finding all matches.
  const headerRegex = /\*\*(Warm-Up.*?|The Thang.*?|6 Minutes of Mary.*?|Circle of Trust.*?)\*\*/g;
  
  // Split the text by the headers. This creates an array where content pieces are between header pieces.
  const parts = markdownText.split(headerRegex);

  // The first part is anything before the first header, which we can ignore.
  // We then iterate through the captured headers and their corresponding content.
  // `parts` will look like: [intro, header1, content1, header2, content2, ...]
  let currentHeader = null;
  let contentBuffer = '';
  
  const textWithHeaders = markdownText.replace(headerRegex, (match) => `%%HEADER%%${match}`);
  const splitByHeaders = textWithHeaders.split('%%HEADER%%');


  for(const part of splitByHeaders) {
    if(!part.trim()) continue;

    if (part.startsWith('**Warm-Up')) {
      sections['WARMUP'] = cleanContent(part.split('**').slice(2).join('**'));
    } else if (part.startsWith('**The Thang')) {
      sections['THE THANG'] = cleanContent(part.split('**').slice(2).join('**'));
    } else if (part.startsWith('**6 Minutes of Mary')) {
      sections['MARY'] = cleanContent(part.split('**').slice(2).join('**'));
    } else if (part.startsWith('**Circle of Trust')) {
      sections['COT'] = cleanContent(part.split('**').slice(2).join('**'));
    }
  }

  return `WARMUP:
${sections['WARMUP']}

THE THANG:
${sections['THE THANG']}

MARY:
${sections['MARY']}

ANNOUNCEMENTS:

COT:
${sections['COT']}`;
};
